### ISSUE TITLE
new entry form has no status bar anymore

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#19]
it doesn't show errors when some field is missing (tags etc.)

**Comment by baudren** [comment]
Wow... so, the problem is actually deeper than the status bar. Whole fields are gone missing! The 'title', 'tags', 'body' fields appear, but not their names!

It seems to stem from a bad interaction between the `translate` method of the `QObject` (`self.tr`), and this import:

~~~ python
from __future__ import unicode_literals
~~~

that I added to have a better compatibility with Python 3. If I remove this import in the `popus.py` file, it then works, but this bugs me. Looking for a better solution.

**Comment by egolus** [comment]
So if I understand correctly, you have to build a translation file and then this function replaces the text from the trnanslation file. if there is no translation it should keep the original string? Have you tried to actually use a translation file? I could do a german translation, if needed.

So the possibilities are:

-

**Comment by baudren** [comment]
Yes, you seem right on the different options. I am reluctant in removing the whole translation opportunity - one never knows. I think I will simply wrap the `tr` function into my own function, which for the moment will not do anything, but could one day call the inbuilt `tr`. This way, all hope is not lost - though the bug report file does look dead.

**Comment by egolus** [comment]
Yes, I was thinking the same. You just have to remenber that you wrapped the `tr` function, when you want to use it again. 
Hopefully, they will fix the bug some day!
