### ISSUE TITLE
Initial window size on windows

### ISSUE THREAD

**Issue by egolus** [baudren/NoteOrganiser#37]
[If there is no saved geometry, you set the window to half width and full height of the screen-area](https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/NoteOrganiser.py#L65-L67). This looks like a straight-forward thing, but on windows, with the taskbar on the bottom, the full height means that the window title-bar moves out of the screen an the user can't grab it to move the window

It's not a big problem, but a bit anoying for users that use *only* the mouse for these things

how does it behave on linux? Is `QtGui.QApplication.desktop().screenGeometry()` only the area that a window can use? (Without taskbars etc.)

**Comment by baudren** [comment]
So, there is a `availableGeometry()` which only returns the proper size, without the taskbar. My commit 878a9a7 addresses this concern.

But this is not the whole story. Another problem arises because Windows (at least, maybe also Linux) "decorates" the window after the `show()` call, with the title bar, and some extra width. I tried to address this problem in the same commit, but I could not think of a clever way of getting only the top decoration to remove it (hence introducing an ad-hoc factor of 3./4). [Inspiration](https://forum.qt.io/topic/41135/solved-qdesktopwindow-availablegeometry-not-excluding-taskbar-qt-5-2-windows-7/7)

Can you take a look and see how it behaves for you, and if you find a better solution?

**Comment by egolus** [comment]
On my notebook, this looks good. It uses half width and full height of the available space. And the whole window is visible! On my desktop computer with two-screen-setup it looks the same.

**Comment by baudren** [comment]
I had the feeling two-screen setups are causing more difficulties... What is the behaviour there? Half width corresponds to one full screen? Or is it the height that is wrong?

**Comment by egolus** [comment]
Sorry, I was too vague. I wanted to say it looks the same as on my laptop, so it looks good. (half of the width, full height of the main screen)

**Comment by baudren** [comment]
Good, so let's leave it at that for the moment! Thanks.
