### ISSUE TITLE
Logging does not work (empty file) with Python 3

### ISSUE THREAD

**Issue by baudren** [baudren/NoteOrganiser#60]

**Comment by egolus** [comment]
do you have any idea yet, what causes this issue? Is the logger itself not py3 compatible?

**Comment by egolus** [comment]
**first test:** 
If I set up the logger as done in `logger.py` in an interactive py3 session, the logger writes to the file

I haven't understood yet how to set the logging level .. could it be that it is set to low so that no message gets written? This would go in line with the fact that the file gets created

**second test:** add messages with different levels
`warn` messages get written. So my assumtion was right. So I think, [this](https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/logger.py#L10-L12) somehow doesn't work and the logger gets created with the wrong level

[here](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) they write the standard log level is `WARNING` (30). The text is the same in the docs for py2, but it looks like we get effective log levels of 20 for py2 and 30 for py3
So I would say, in py2 setting the level to `INFO` is successful, in py3 it fails, so it stays on the standard (`WARNING`)

As a simple fix I would write the existing loglevels in a list and check the string against that list instead of the logger-internal strings

**Comment by baudren** [comment]
:oO: I don't remember what I did on these [three lines](https://github.com/baudren/NoteOrganiser/blob/devel/noteorganiser/logger.py#L10-L12)...

I think that a simpler way would be to do

``` python
    level_value = getattr(logging, level)
```

**Comment by egolus** [comment]
https://github.com/baudren/NoteOrganiser/compare/60-py3logging
(I allways need you to tell me to use `getattr`)

**Comment by baudren** [comment]
Merge, thanks
